title: "Yufei Gu's personal website"
author: "Yufei Gu"
email: "yufei.gu.451@outlook.com"
description: "PhD student in learning theory and optimization building efficient optimizers and generalization tools for deep learning and LLMs."
url: "https://yufei-gu-451.github.io"
baseurl: ""
header_pages:
  - index.md
  - publications.md
  - cv.md

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/

# Include files
include:
  - _pages